### ISSUE TITLE
dedicated struct/union/enum forms in rust decl layer

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/a-mir-formality#46]
Currently we have one declaration for all ADTs in the decl grammar:

https://github.com/nikomatsakis/a-mir-formality/blob/81ba52b8695db7f87f50b0916940b2bb41fe6d59/src/decl/grammar.rkt#L27-L31

resulting instances like this

```
    (; struct Foo { }
     AdtDecl_Foo (term (Foo (struct
                              () ; no generic parameters
                              () ; no where clauses
                              ((Foo ())) ; the 1 variant (named `Foo`)
                              ))))
```

it might be cool to introduce `StructDecl`, `EnumDecl`, and friends. We could still factor out the common code by introducing some helper functions to convert those into an "adt decl". Then we could write:

```
    (; struct Foo { }
     StructDecl_Foo (term (Foo (struct
                              () ; no generic parameters
                              () ; no where clauses
                              () ; list of fields
                              ))))
```

it's a minor thing, but not having to introduce a "dummy variant" would feel a lot more Rust-like to me.

**Comment by shua** [comment]
I guess this is completed? https://github.com/rust-lang/a-mir-formality/blob/main/crates/formality-rust/src/grammar.rs#L55-L58
