### ISSUE TITLE
Possible unused require

### ISSUE THREAD

**Issue by pierwill** [rust-lang/a-mir-formality#96]
This code might be unused: https://github.com/nikomatsakis/a-mir-formality/blob/4a47eb8d97a374a953d50a94acab55d4c98ac552/racket-src/logic/test/cosld-solve-ambiguity.rkt#L3

That's what racket-mode is telling me, at least. 😇

**Comment by shua** [comment]
This doesn't seem relevant anymore. I guess this ticket can be closed?
